**Abby Ortego**

**CMPS 6790 Data Science**

**Milestone 1**

# Imports

In [13]:
import requests
from bs4 import BeautifulSoup
import regex as re
import pandas as pd

# Motivation

[Magic: The Gathering](https://magic.wizards.com/en/intro) is a popular trading card game with competitive tournaments hosted around the globe. During the tournaments, players create their own decks (possibly inspired by existing ones) and battle one another until one lone victor remains. 

This yields the question: what makes a winning deck? 

The community is divided by this. Some would (naively) say it's the price of the cards in the deck while others would argue properties on the cards hold more sway. This notebook is the first step into answering this question with methods grounded in statistical reasoning.

# Extracting, Transforming, and Loading the Data

To answer this question, we need access to tournament data from Magic: The Gathering events. If we can collect the decks that were used in the tournaments and how they fared, we can start making informed guesses. 

Thankfully, [MTG Top 8](https://mtgtop8.com/) compiles this data from reliable tournament reporting services (e.g., [Melee](https://melee.gg/), [Magic Events](https://magic.gg/), etc.). This site does not offer an API to collect this data, though, so we will have to scrape their pages for the data we're interested in. The site's [policies](https://mtgtop8.com/privacy) do not ban web scrapers.

## Getting Tournament Data

MTG Top 8 organizes decks by tournament, so we will first need to compile a list of tournaments and their links on the site. Magic: The Gathering is quite popular, though, with a variety of play formats and tournaments hosted all around the globe, so grabbing data for *all* tournaments on the site is not feasible. 

For this notebook, we will focus only on major tournaments played in the Standard format during the last month. [Explain why you chose this scope].

This [link](https://mtgtop8.com/format?f=ST&meta=46&a=) lists all major tournaments in the last two months in the "Last 20 Events" table. This is close to what we're interested in! 

This table only displays 20 items at a time, though, which means we'll have to loop over the pages and scrape this table for each one.

In [3]:
# get all tournaments tables
tournaments_tables = []
for page in range(1, 7):    # there are roughly 6 pages worth of data
    r = requests.get(f"https://mtgtop8.com/format?f=ST&meta=46&cp={page}")
    if r.status_code != 200:
        print(f"Could not scrape events from page {page}.")
        continue
    #

    soup = BeautifulSoup(r.content)
    tables = soup.find_all("table")     # using soup to grab all tables on the page
    tournaments_tables.append(tables[2])   # the table we're interested in is the third one on the page 
#
display(tournaments_tables)

[<table align="center" border="0" class="Stable" width="98%">
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80490&amp;f=ST">MTGO Challenge 32</a> <span class="new">NEW</span></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">15/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=80514&amp;f=ST">South America Regional Championship Santiago 2026 - Devir </a> @ <a class="und" href="event?e=80514&amp;f=ST">Santiago (Chile)</a> <span class="new">NEW</span></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">14/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80415&amp;f=ST">MTGO Challenge 32</a> <span class="new">NEW</span></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">14/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80394&amp;f=ST">MTGO Challenge 32</a> <span class="new">NEW</span></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">14/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80393&amp;f=ST">MTGO Challenge 64</a> <span class="new">NEW</span></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">13/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80372&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">13/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80328&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">12/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80293&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">10/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80250&amp;f=ST">MTGO Challenge 64</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">09/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80147&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">08/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=80087&amp;f=ST">RCQ</a> @ <a class="und" href="event?e=80087&amp;f=ST">Playtime (Merate, Italy)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">08/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80126&amp;f=ST">MTGO Showcase Challenge</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">07/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80125&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">07/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80046&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">07/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80065&amp;f=ST">MTGO Challenge 64</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">06/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80029&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">06/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79976&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">05/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79952&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">03/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79924&amp;f=ST">MTGO Challenge 64</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">02/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79877&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">01/02/26</td>
 </tr>
 </table>,
 <table align="center" border="0" class="Stable" width="98%">
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79818&amp;f=ST">RCQ</a> @ <a class="und" href="event?e=79818&amp;f=ST">Draco Hobby Center (Bogota, Colombia)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">01/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79819&amp;f=ST">MTGO RC Super Qualifier</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">01/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79854&amp;f=ST">2nd Chance PTQ</a> @ <a class="und" href="event?e=79854&amp;f=ST">Pro Tour Lorwyn Eclipsed (Richmond, VA)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">31/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79785&amp;f=ST">Champions Cup Special Qualifier</a> @ <a class="und" href="event?e=79785&amp;f=ST">Kawasaki (Japan)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">30/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79746&amp;f=ST">Pro Tour Lorwyn Eclipsed</a> @ <a class="und" href="event?e=79746&amp;f=ST">Richmond</a></td>
 <td align="center" width="13%"><img height="20" src="/graph/bigstar.png"/></td>
 <td align="right" class="S12" width="12%">30/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79745&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">30/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79719&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">30/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79671&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">29/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79666&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">27/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79651&amp;f=ST">MTGO Challenge 64</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">26/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79664&amp;f=ST">Saturday ReCQ #2</a> @ <a class="und" href="event?e=79664&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79600&amp;f=ST">Super Sunday RCQ #2</a> @ <a class="und" href="event?e=79600&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79599&amp;f=ST">Super Sunday RCQ #1</a> @ <a class="und" href="event?e=79599&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtga.png" title="MTG Arena"/></td>
 <td class="S14" width="70%"><a href="event?e=79598&amp;f=ST">Izzet Explosive Experiment Event</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79563&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79462&amp;f=ST">Regional Championship</a> @ <a class="und" href="event?e=79462&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79569&amp;f=ST">Saturday RCQ</a> @ <a class="und" href="event?e=79569&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">24/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79482&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">24/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79476&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">24/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79428&amp;f=ST">RCQ</a> @ <a class="und" href="event?e=79428&amp;f=ST">BB-Spiele (Rosenheim, Germany)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">24/01/26</td>
 </tr>
 </table>,
 <table align="center" border="0" class="Stable" width="98%">
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79391&amp;f=ST">RCQ</a> @ <a class="und" href="event?e=79391&amp;f=ST">Back to Games (Dubai, UAE)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">24/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79568&amp;f=ST">Friday Standard LCQ #16</a> @ <a class="und" href="event?e=79568&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79567&amp;f=ST">Friday Standard LCQ #15</a> @ <a class="und" href="event?e=79567&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79566&amp;f=ST">Friday Standard LCQ #14</a> @ <a class="und" href="event?e=79566&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79523&amp;f=ST">MTGO Challenge 64</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79453&amp;f=ST">Friday Standard LCQ #13</a> @ <a class="und" href="event?e=79453&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79450&amp;f=ST">Friday Standard LCQ #12</a> @ <a class="und" href="event?e=79450&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79451&amp;f=ST">Friday Standard LCQ #11</a> @ <a class="und" href="event?e=79451&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>

Now that we have the tournament tables, we can extract the information we're interested in from the html. We're looking for...
- *Tournament Name* to help us identify tournaments 
- *Tournament Date* to help us only grab tournaments in the last month
- *Link to Additional Tournament Information* to help us grab ranking information later

**(1) Tournament Names and Dates** are stored as text within the html tags, so we can use BeautifulSoup's `get_text()` method to extract this information from the table. When you do you get a string that looks like this:

`'\n\n\nRCQ @ Draco Hobby Center (Bogota, Colombia)\n\n01/02/26\n\n\n\nMTGO RC Super Qualifier\n\n01/02/26\n\n\n\n2nd Chance PTQ @ Pro Tour Lorwyn Eclipsed (Richmond, VA)\n\n31/01/26\n\n\n\n`

It's not very pretty but the new line characters do have a pattern! 3-4 new line characters separate tournaments and 2 new line characters separate tournament name from date. We can use regex to split the string on every 3-4 or 2 new line characters. 

This yields a list where every even indexed item is a tournament name and every odd indexed item is a tournament date. They can be split using list slicing to get names and dates separately while still respecting order so that no information gets lost or confused.

**(2) Links to Additional Tournament Information** are stored in `a` tags with an `href` property. Some entries in the table record an additional `a` tag with a the `class` property specified in addition to `href`. These tags have duplicate information that we don't need. We can use BeautifulSoup's `find_all()` method to find all `a` tags that have an `href` property specified but no `class` property.

Lastly, we can use the `get()` method to extract the links.

Below loops through the html for the tournament tables and performs the actions outlined in **(1)** and **(2)** above.

In [38]:
# lists to store this information
names = []
dates = []
links = []

for tournaments_table in tournaments_tables:
    # (1) Tournament Names and Date
    table_text = tournaments_table.get_text()
    name_dates = re.split("\\n{3,4}|\\n{2}", table_text)[1:-1]   # the first and last item are blank from splitting 
    names.extend(name_dates[::2])     # gets all even indexed items (start at position 0 with step size 2)
    dates.extend(name_dates[1::2])      # gets all odd indexed items (start at position 1 with step size 2)

    # (2) Links to Additional Tournament Information
    table_hrefs = tournaments_table.find_all("a", href=True, class_=False)
    links.extend([table_href.get("href") for table_href in table_hrefs])
#

display(names, dates, links)

['MTGO Challenge 32 NEW',
 'South America Regional Championship Santiago 2026 - Devir  @ Santiago (Chile) NEW',
 'MTGO Challenge 32 NEW',
 'MTGO Challenge 32 NEW',
 'MTGO Challenge 64 NEW',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 64',
 'MTGO Challenge 32',
 'RCQ @ Playtime (Merate, Italy)',
 'MTGO Showcase Challenge',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 64',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 64',
 'MTGO Challenge 32',
 'RCQ @ Draco Hobby Center (Bogota, Colombia)',
 'MTGO RC Super Qualifier',
 '2nd Chance PTQ @ Pro Tour Lorwyn Eclipsed (Richmond, VA)',
 'Champions Cup Special Qualifier @ Kawasaki (Japan)',
 'Pro Tour Lorwyn Eclipsed @ Richmond',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 64',
 'Saturday ReCQ #2 @ SCG CON Portland',
 'Super Sunday RCQ #2 @ SCG CON Portland',
 'Super Sunday RCQ #1 @ SCG CON Portland',
 'Izzet Explosive Experiment Event',
 'MTGO Challenge 32',
 'Regional Championship @ SCG CON Portland',
 'Saturday RCQ @ SCG CON Portland',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'RCQ @ BB-Spiele (Rosenheim, Germany)',
 'RCQ @ Back to Games (Dubai, UAE)',
 'Friday Standard LCQ #16 @ SCG CON Portland',
 'Friday Standard LCQ #15 @ SCG CON Portland',
 'Friday Standard LCQ #14 @ SCG CON Portland',
 'MTGO Challenge 64',
 'Friday Standard LCQ #13 @ SCG CON Portland',
 'Friday Standard LCQ #12 @ SCG CON Portland',
 'Friday Standard LCQ #11 @ SCG CON Portland',
 'Friday Standard LCQ #10 @ SCG CON Portland',
 'Friday Standard LCQ #9 @ SCG CON Portland',
 'Friday Standard LCQ #8 @ SCG CON Portland',
 'Friday Standard LCQ #7 @ SCG CON Portland',
 'Friday Standard LCQ #6 @ SCG CON Portland',
 'Friday Standard LCQ #5 @ SCG CON Portland',
 'Friday Standard LCQ #4 @ SCG CON Portland',
 'Friday Standard LCQ #3 @ SCG CON Portland',
 'Friday Standard LCQ #2 @ SCG CON Portland',
 'Friday Standard LCQ #1 @ SCG CON Portland',
 'Champions Cup Season Special Qualifier @ Kawasaki (Japan)',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 64',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 64',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 64',
 'Super Sunday RCQ @ SCG CON Atlanta',
 'Sunday ReCQ @ SCG CON Atlanta',
 'Sunday Destination Qualifier - Fanfinity @ Spotlight (Lyon, France)',
 'MTGO Showcase Challenge',
 'MTGO Challenge 32',
 'RCQ @ Il Labirinto (Bollate, Milan)',
 'Saturday ReCQ @ SCG CON Atlanta',
 'Magic Spotlight: The Avatar @ SCG CON Atlanta',
 'Main Event - Magic Spotlight Series - Fanfinity @ Spotlight (Lyon, France)',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'Champions Cup Special Qualifier @ Kawasaki (Japan)',
 'Friday ReCQ #3 @ SCG CON Atlanta',
 'Friday ReCQ #2 @ SCG CON Atlanta',
 'Friday ReCQ #1 @ SCG CON Atlanta',
 'MTGO Challenge 64',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 64',
 'FullFire/GYDO Invitational 1K',
 'RCQ @ Cardboard Horde (Sidney, OH)',
 'MTGO Challenge 32',
 'RCQ @ Boardwalk Games (Carrollton, TX)',
 'RCQ @ BB-Spiele (Rosenheim, Germany)',
 'RCQ @ Tier 1 Games (Kokomo, IN)',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO Challenge 64',
 'MTGO Challenge 32',
 'Champions Cup Special Qualifier @ Nagoya (Japan)',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'MTGO RC Super Qualifier',
 'MTGO Challenge 32',
 'Champions Cup Special Qualifier @ Kichijoji (Japan)',
 'Champions Cup Season 4 Round 3 Special Qualifier @ Chiba (Japan)',
 'Champions Cup Special Qualifier @ Nagoya (Japan)',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 'The 32nd God of Standard Tournament @ TC (Tokyo, Japan)',
 'MTGO Challenge 64',
 'MTGO Challenge 32',
 'Champions Cup Special Qualifier @ Osu (Japan)',
 'MTGO Challenge 32',
 'MTGO Challenge 32',
 "RCQ @ SpellCrafter's Den (Upper Sandusky, OH)",
 'Champions Cup Special Qualifier @ TC (Osaka, Japan)',
 'MTGO Challenge 32']

['15/02/26',
 '14/02/26',
 '14/02/26',
 '14/02/26',
 '13/02/26',
 '13/02/26',
 '12/02/26',
 '10/02/26',
 '09/02/26',
 '08/02/26',
 '08/02/26',
 '07/02/26',
 '07/02/26',
 '07/02/26',
 '06/02/26',
 '06/02/26',
 '05/02/26',
 '03/02/26',
 '02/02/26',
 '01/02/26',
 '01/02/26',
 '01/02/26',
 '31/01/26',
 '30/01/26',
 '30/01/26',
 '30/01/26',
 '30/01/26',
 '29/01/26',
 '27/01/26',
 '26/01/26',
 '25/01/26',
 '25/01/26',
 '25/01/26',
 '25/01/26',
 '25/01/26',
 '25/01/26',
 '24/01/26',
 '24/01/26',
 '24/01/26',
 '24/01/26',
 '24/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '23/01/26',
 '22/01/26',
 '20/01/26',
 '19/01/26',
 '18/01/26',
 '17/01/26',
 '17/01/26',
 '16/01/26',
 '16/01/26',
 '15/01/26',
 '13/01/26',
 '12/01/26',
 '11/01/26',
 '11/01/26',
 '11/01/26',
 '11/01/26',
 '11/01/26',
 '11/01/26',
 '10/01/26',
 '10/01/26',
 '10/01/26',
 '10/01/26',
 '10/01/26',
 '09/01/26',
 '09/01/26',
 '09/01/26',
 '09/01/26',
 '09/01/26',
 '09/01/26',
 '08/01/26',
 '06/01/26',
 '05/01/26',
 '04/01/26',
 '04/01/26',
 '04/01/26',
 '03/01/26',
 '03/01/26',
 '03/01/26',
 '03/01/26',
 '03/01/26',
 '02/01/26',
 '02/01/26',
 '01/01/26',
 '01/01/26',
 '30/12/25',
 '29/12/25',
 '29/12/25',
 '28/12/25',
 '27/12/25',
 '27/12/25',
 '27/12/25',
 '27/12/25',
 '26/12/25',
 '26/12/25',
 '26/12/25',
 '25/12/25',
 '25/12/25',
 '21/12/25',
 '20/12/25',
 '20/12/25',
 '20/12/25']

['event?e=80490&f=ST',
 'event?e=80514&f=ST',
 'event?e=80415&f=ST',
 'event?e=80394&f=ST',
 'event?e=80393&f=ST',
 'event?e=80372&f=ST',
 'event?e=80328&f=ST',
 'event?e=80293&f=ST',
 'event?e=80250&f=ST',
 'event?e=80147&f=ST',
 'event?e=80087&f=ST',
 'event?e=80126&f=ST',
 'event?e=80125&f=ST',
 'event?e=80046&f=ST',
 'event?e=80065&f=ST',
 'event?e=80029&f=ST',
 'event?e=79976&f=ST',
 'event?e=79952&f=ST',
 'event?e=79924&f=ST',
 'event?e=79877&f=ST',
 'event?e=79818&f=ST',
 'event?e=79819&f=ST',
 'event?e=79854&f=ST',
 'event?e=79785&f=ST',
 'event?e=79746&f=ST',
 'event?e=79745&f=ST',
 'event?e=79719&f=ST',
 'event?e=79671&f=ST',
 'event?e=79666&f=ST',
 'event?e=79651&f=ST',
 'event?e=79664&f=ST',
 'event?e=79600&f=ST',
 'event?e=79599&f=ST',
 'event?e=79598&f=ST',
 'event?e=79563&f=ST',
 'event?e=79462&f=ST',
 'event?e=79569&f=ST',
 'event?e=79482&f=ST',
 'event?e=79476&f=ST',
 'event?e=79428&f=ST',
 'event?e=79391&f=ST',
 'event?e=79568&f=ST',
 'event?e=79567&f=ST',
 'event?e=79566&f=ST',
 'event?e=79523&f=ST',
 'event?e=79453&f=ST',
 'event?e=79450&f=ST',
 'event?e=79451&f=ST',
 'event?e=79455&f=ST',
 'event?e=79448&f=ST',
 'event?e=79457&f=ST',
 'event?e=79447&f=ST',
 'event?e=79446&f=ST',
 'event?e=79456&f=ST',
 'event?e=79445&f=ST',
 'event?e=79452&f=ST',
 'event?e=79449&f=ST',
 'event?e=79454&f=ST',
 'event?e=79458&f=ST',
 'event?e=79338&f=ST',
 'event?e=79307&f=ST',
 'event?e=79281&f=ST',
 'event?e=79243&f=ST',
 'event?e=79173&f=ST',
 'event?e=79106&f=ST',
 'event?e=79104&f=ST',
 'event?e=79103&f=ST',
 'event?e=79065&f=ST',
 'event?e=79044&f=ST',
 'event?e=79005&f=ST',
 'event?e=78949&f=ST',
 'event?e=78984&f=ST',
 'event?e=78983&f=ST',
 'event?e=78947&f=ST',
 'event?e=78873&f=ST',
 'event?e=78872&f=ST',
 'event?e=78848&f=ST',
 'event?e=78912&f=ST',
 'event?e=78892&f=ST',
 'event?e=78891&f=ST',
 'event?e=78802&f=ST',
 'event?e=78778&f=ST',
 'event?e=78890&f=ST',
 'event?e=78852&f=ST',
 'event?e=78850&f=ST',
 'event?e=78849&f=ST',
 'event?e=78787&f=ST',
 'event?e=78759&f=ST',
 'event?e=78727&f=ST',
 'event?e=78716&f=ST',
 'event?e=78666&f=ST',
 'event?e=78679&f=ST',
 'event?e=78668&f=ST',
 'event?e=78620&f=ST',
 'event?e=78728&f=ST',
 'event?e=78607&f=ST',
 'event?e=78576&f=ST',
 'event?e=78577&f=ST',
 'event?e=78536&f=ST',
 'event?e=78619&f=ST',
 'event?e=78532&f=ST',
 'event?e=78554&f=ST',
 'event?e=78488&f=ST',
 'event?e=78479&f=ST',
 'event?e=78440&f=ST',
 'event?e=78439&f=ST',
 'event?e=78454&f=ST',
 'event?e=78414&f=ST',
 'event?e=78413&f=ST',
 'event?e=78367&f=ST',
 'event?e=78363&f=ST',
 'event?e=78482&f=ST',
 'event?e=78362&f=ST',
 'event?e=78344&f=ST',
 'event?e=78366&f=ST',
 'event?e=78314&f=ST',
 'event?e=78269&f=ST',
 'event?e=78209&f=ST',
 'event?e=78207&f=ST',
 'event?e=78173&f=ST']

We can load this data into a panda's dataframe so we can start transforming it.

In [39]:
all_tournaments_df = pd.DataFrame({'Name': names, 'Date': dates, 'Link': links})
display(all_tournaments_df, all_tournaments_df.dtypes)

,Name,Date,Link
0,MTGO Challenge 32 NEW,15/02/26,event?e=80490&f=ST
1,South America Regional Championship Santiago 2...,14/02/26,event?e=80514&f=ST
2,MTGO Challenge 32 NEW,14/02/26,event?e=80415&f=ST
3,MTGO Challenge 32 NEW,14/02/26,event?e=80394&f=ST
4,MTGO Challenge 64 NEW,13/02/26,event?e=80393&f=ST
...,...,...,...
115,MTGO Challenge 32,25/12/25,event?e=78314&f=ST
116,MTGO Challenge 32,21/12/25,event?e=78269&f=ST
117,"RCQ @ SpellCrafter's Den (Upper Sandusky, OH)",20/12/25,event?e=78209&f=ST
118,"Champions Cup Special Qualifier @ TC (Osaka, J...",20/12/25,event?e=78207&f=ST
119,MTGO Challenge 32,20/12/25,event?e=78173&f=ST

Name    str
Date    str
Link    str
dtype: object

Finally, the dataframe above has *all* large tournaments in the last two months, but this wasn't quite what we were interested in so it needs some polishing.

First, some of these tournaments include Magic: The Gathering games played online in the app which has a similar but alternative system for collecting cards and creating decks. Due to this we want to only look at tournaments played outside of the app in live tournaments.

Thankfully, these online tournaments are denoted with "MTGO" so we can filter the `Name` property of the `tournaments_df` to only include tournaments without "MTGO" in the name.

In [40]:
# all tournaments that are not online (i.e., do not include "MTGO")
not_online = ~all_tournaments_df["Name"].str.contains("MTGO")

Secondly, we are only concerned with tournaments that occurred in the last full month (as of this milestone this is January 2026), so we'll filter tournaments from before or after that time out as well. This will also allow us to convert our `Date` column in the pandas dataframe to the proper type (datetime).

In [41]:
# format to datetime
all_tournaments_df["Date"] = pd.to_datetime(all_tournaments_df["Date"], format="%d/%m/%y")

# all tournaments in january
in_january = (all_tournaments_df["Date"] >= '2026-01-01') & (all_tournaments_df["Date"] < '2026-02-01')

Thirdly, the `Link` contains only the suffix of the URL. We need to append the base URL ("https://mtgtop8.com") to this column for easy access later.

In [42]:
# adding base_url to links
base_url = "https://mtgtop8.com"
all_tournaments_df["Link"] = base_url + '/' + all_tournaments_df["Link"]

When putting it all together you get the following tournament dataframe.

In [43]:
# applying our filters
tournaments_df = all_tournaments_df[not_online & in_january].reset_index(drop=True)

display(tournaments_df, tournaments_df.dtypes)

,Name,Date,Link
0,2nd Chance PTQ @ Pro Tour Lorwyn Eclipsed (Ric...,2026-01-31,https://mtgtop8.com/event?e=79854&f=ST
1,Champions Cup Special Qualifier @ Kawasaki (Ja...,2026-01-30,https://mtgtop8.com/event?e=79785&f=ST
2,Pro Tour Lorwyn Eclipsed @ Richmond,2026-01-30,https://mtgtop8.com/event?e=79746&f=ST
3,Saturday ReCQ #2 @ SCG CON Portland,2026-01-25,https://mtgtop8.com/event?e=79664&f=ST
4,Super Sunday RCQ #2 @ SCG CON Portland,2026-01-25,https://mtgtop8.com/event?e=79600&f=ST
5,Super Sunday RCQ #1 @ SCG CON Portland,2026-01-25,https://mtgtop8.com/event?e=79599&f=ST
6,Izzet Explosive Experiment Event,2026-01-25,https://mtgtop8.com/event?e=79598&f=ST
7,Regional Championship @ SCG CON Portland,2026-01-25,https://mtgtop8.com/event?e=79462&f=ST
8,Saturday RCQ @ SCG CON Portland,2026-01-24,https://mtgtop8.com/event?e=79569&f=ST
9,"RCQ @ BB-Spiele (Rosenheim, Germany)",2026-01-24,https://mtgtop8.com/event?e=79428&f=ST
10,"RCQ @ Back to Games (Dubai, UAE)",2026-01-24,https://mtgtop8.com/event?e=79391&f=ST
11,Friday Standard LCQ #16 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79568&f=ST
12,Friday Standard LCQ #15 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79567&f=ST
13,Friday Standard LCQ #14 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79566&f=ST
14,Friday Standard LCQ #13 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79453&f=ST
15,Friday Standard LCQ #12 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79450&f=ST
16,Friday Standard LCQ #11 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79451&f=ST
17,Friday Standard LCQ #10 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79455&f=ST
18,Friday Standard LCQ #9 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79448&f=ST
19,Friday Standard LCQ #8 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79457&f=ST
20,Friday Standard LCQ #7 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79447&f=ST
21,Friday Standard LCQ #6 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79446&f=ST
22,Friday Standard LCQ #5 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79456&f=ST
23,Friday Standard LCQ #4 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79445&f=ST
24,Friday Standard LCQ #3 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79452&f=ST
25,Friday Standard LCQ #2 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79449&f=ST
26,Friday Standard LCQ #1 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79454&f=ST
27,Champions Cup Season Special Qualifier @ Kawas...,2026-01-23,https://mtgtop8.com/event?e=79458&f=ST
28,Super Sunday RCQ @ SCG CON Atlanta,2026-01-11,https://mtgtop8.com/event?e=78984&f=ST
29,Sunday ReCQ @ SCG CON Atlanta,2026-01-11,https://mtgtop8.com/event?e=78983&f=ST
30,Sunday Destination Qualifier - Fanfinity @ Spo...,2026-01-11,https://mtgtop8.com/event?e=78947&f=ST
31,"RCQ @ Il Labirinto (Bollate, Milan)",2026-01-11,https://mtgtop8.com/event?e=78848&f=ST
32,Saturday ReCQ @ SCG CON Atlanta,2026-01-10,https://mtgtop8.com/event?e=78912&f=ST
33,Magic Spotlight: The Avatar @ SCG CON Atlanta,2026-01-10,https://mtgtop8.com/event?e=78892&f=ST
34,Main Event - Magic Spotlight Series - Fanfinit...,2026-01-10,https://mtgtop8.com/event?e=78891&f=ST
35,Champions Cup Special Qualifier @ Kawasaki (Ja...,2026-01-09,https://mtgtop8.com/event?e=78890&f=ST
36,Friday ReCQ #3 @ SCG CON Atlanta,2026-01-09,https://mtgtop8.com/event?e=78852&f=ST
37,Friday ReCQ #2 @ SCG CON Atlanta,2026-01-09,https://mtgtop8.com/event?e=78850&f=ST
38,Friday ReCQ #1 @ SCG CON Atlanta,2026-01-09,https://mtgtop8.com/event?e=78849&f=ST
39,FullFire/GYDO Invitational 1K,2026-01-04,https://mtgtop8.com/event?e=78679&f=ST
40,"RCQ @ Cardboard Horde (Sidney, OH)",2026-01-04,https://mtgtop8.com/event?e=78668&f=ST
41,"RCQ @ Boardwalk Games (Carrollton, TX)",2026-01-03,https://mtgtop8.com/event?e=78728&f=ST
42,"RCQ @ BB-Spiele (Rosenheim, Germany)",2026-01-03,https://mtgtop8.com/event?e=78607&f=ST
43,"RCQ @ Tier 1 Games (Kokomo, IN)",2026-01-03,https://mtgtop8.com/event?e=78576&f=ST
44,Champions Cup Special Qualifier @ Nagoya (Japan),2026-01-01,https://mtgtop8.com/event?e=78554&f=ST

Name               str
Date    datetime64[us]
Link               str
dtype: object

All in all, we're left with 44 tournaments to grab additional information for (e.g., deck rankings, prices, etc.)

## Getting Additional Tournament Details

# Exploratory Data Analysis

# Future Work